<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContractSettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            // Contract System Settings
            [
                'key' => 'contracts.default_expiration_days',
                'display_name' => 'Default Contract Expiration (Days)',
                'value' => '365',
                'details' => 'Number of days until a contract expires by default. Can be overridden per contract.',
                'type' => 'text',
                'order' => 1,
                'group' => 'Contracts',
            ],
            [
                'key' => 'contracts.signature_expiration_days',
                'display_name' => 'Signature Request Expiration (Days)',
                'value' => '14',
                'details' => 'Number of days until a signature request expires if not signed.',
                'type' => 'text',
                'order' => 2,
                'group' => 'Contracts',
            ],
            [
                'key' => 'contracts.reminder_frequency_days',
                'display_name' => 'Signature Reminder Frequency (Days)',
                'value' => '3',
                'details' => 'How often to send reminder emails for pending signatures (in days).',
                'type' => 'text',
                'order' => 3,
                'group' => 'Contracts',
            ],
            [
                'key' => 'contracts.contract_number_prefix',
                'display_name' => 'Contract Number Prefix',
                'value' => 'CONT',
                'details' => 'Prefix for auto-generated contract numbers (e.g., CONT-2025-001).',
                'type' => 'text',
                'order' => 4,
                'group' => 'Contracts',
            ],
            [
                'key' => 'contracts.enable_versioning',
                'display_name' => 'Enable Contract Versioning',
                'value' => '1',
                'details' => 'Track all changes made to contracts with version history.',
                'type' => 'checkbox',
                'order' => 5,
                'group' => 'Contracts',
            ],
            [
                'key' => 'contracts.enable_comments',
                'display_name' => 'Enable Contract Comments',
                'value' => '1',
                'details' => 'Allow users to comment on contracts.',
                'type' => 'checkbox',
                'order' => 6,
                'group' => 'Contracts',
            ],
            [
                'key' => 'contracts.default_template_visibility',
                'display_name' => 'Default Template Visibility',
                'value' => 'private',
                'details' => 'Default visibility for new templates: public or private.',
                'type' => 'text',
                'order' => 7,
                'group' => 'Contracts',
            ],
            [
                'key' => 'contracts.legal_disclaimer',
                'display_name' => 'Legal Disclaimer Text',
                'value' => 'This electronic signature is legally binding and has the same legal effect as a handwritten signature.',
                'details' => 'Disclaimer text shown on signature pages.',
                'type' => 'textarea',
                'order' => 8,
                'group' => 'Contracts',
            ],
            [
                'key' => 'contracts.require_email_verification',
                'display_name' => 'Require Email Verification for Signatures',
                'value' => '1',
                'details' => 'Signers must verify their email before signing.',
                'type' => 'checkbox',
                'order' => 9,
                'group' => 'Contracts',
            ],
            [
                'key' => 'contracts.auto_complete_when_signed',
                'display_name' => 'Auto-Complete When Fully Signed',
                'value' => '1',
                'details' => 'Automatically mark contracts as completed when all signatures are collected.',
                'type' => 'checkbox',
                'order' => 10,
                'group' => 'Contracts',
            ],
            [
                'key' => 'contracts.enable_pdf_watermark',
                'display_name' => 'Enable PDF Watermark',
                'value' => '1',
                'details' => 'Add watermark to draft and cancelled contracts.',
                'type' => 'checkbox',
                'order' => 11,
                'group' => 'Contracts',
            ],
            [
                'key' => 'contracts.pdf_footer_text',
                'display_name' => 'PDF Footer Text',
                'value' => 'Generated by {{ config(\'app.name\') }} - {{ now()->format(\'Y-m-d H:i:s\') }}',
                'details' => 'Footer text for generated PDFs. Supports variables: {{ app.name }}, {{ now() }}.',
                'type' => 'text',
                'order' => 12,
                'group' => 'Contracts',
            ],

            // Email Settings for Contracts
            [
                'key' => 'contracts.email.from_name',
                'display_name' => 'Contract Email From Name',
                'value' => config('app.name', 'EvenLeads'),
                'details' => 'Name used in contract notification emails.',
                'type' => 'text',
                'order' => 13,
                'group' => 'Contracts - Email',
            ],
            [
                'key' => 'contracts.email.reply_to',
                'display_name' => 'Contract Email Reply-To',
                'value' => config('mail.from.address', 'noreply@example.com'),
                'details' => 'Reply-to email for contract notifications.',
                'type' => 'text',
                'order' => 14,
                'group' => 'Contracts - Email',
            ],
            [
                'key' => 'contracts.email.signature_request_subject',
                'display_name' => 'Signature Request Email Subject',
                'value' => 'Signature Requested: {{contract_title}}',
                'details' => 'Subject line for signature request emails. Use {{contract_title}} for contract name.',
                'type' => 'text',
                'order' => 15,
                'group' => 'Contracts - Email',
            ],
            [
                'key' => 'contracts.email.enable_branding',
                'display_name' => 'Enable Email Branding',
                'value' => '1',
                'details' => 'Include company logo and colors in contract emails.',
                'type' => 'checkbox',
                'order' => 16,
                'group' => 'Contracts - Email',
            ],

            // Compliance and Security
            [
                'key' => 'contracts.data_retention_days',
                'display_name' => 'Data Retention Period (Days)',
                'value' => '2555',
                'details' => 'How long to retain contracts after completion (7 years = 2555 days). Use 0 for indefinite.',
                'type' => 'text',
                'order' => 17,
                'group' => 'Contracts - Compliance',
            ],
            [
                'key' => 'contracts.enable_audit_log',
                'display_name' => 'Enable Audit Logging',
                'value' => '1',
                'details' => 'Log all contract operations for compliance and security.',
                'type' => 'checkbox',
                'order' => 18,
                'group' => 'Contracts - Compliance',
            ],
            [
                'key' => 'contracts.require_2fa_for_signing',
                'display_name' => 'Require 2FA for High-Value Contracts',
                'value' => '0',
                'details' => 'Require two-factor authentication for contracts over a certain value.',
                'type' => 'checkbox',
                'order' => 19,
                'group' => 'Contracts - Compliance',
            ],
            [
                'key' => 'contracts.high_value_threshold',
                'display_name' => 'High-Value Contract Threshold',
                'value' => '10000',
                'details' => 'Contract value threshold for requiring 2FA (in dollars).',
                'type' => 'text',
                'order' => 20,
                'group' => 'Contracts - Compliance',
            ],
        ];

        foreach ($settings as $setting) {
            DB::table('settings')->updateOrInsert(
                ['key' => $setting['key']],
                array_merge($setting, [
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }

        $this->command->info('Contract settings seeded successfully!');
    }
}
